services:
  minio:
    image: minio/minio:latest
    container_name: minio

    ports:
      - "9100:9000"   # S3 API
      - "9101:9001"   # Web Console

    environment:
      MINIO_ROOT_USER: ${HOOTERS3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${HOOTERS3_SECRET_ACCESS_KEY}

    volumes:
      - ./data/minio:/data

    command: server /data --console-address ":9001"

    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 ${HOOTERS3_ACCESS_KEY_ID} ${HOOTERS3_SECRET_ACCESS_KEY}; do
        sleep 1;
      done;
      mc mb --ignore-existing myminio/product-images;
      exit 0;
      "

  mariadb:
    image: mariadb:11.8
    container_name: hooter-db

    ports:
      - "3308:3306"

    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${HOOTER_DB}
      MARIADB_USER: ${HOOTER_DB_USER}
      MARIADB_PASSWORD: ${HOOTER_DB_PASSWORD}

    volumes:
      - ./data/mariadb:/var/lib/mysql

    restart: unless-stopped


  mongodb:
    image: mongo:8
    container_name: hooter-mongo
    ports:
      - "27000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped


  hooter:
    build: .
    container_name: hooter-backend
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - mariadb
      - minio
    env_file:
      - .env
    ports:
      - ${HOOTER_APPLICATION_PORT}:${HOOTER_APPLICATION_PORT}
    restart: unless-stopped
